#!/bin/zsh
source "$(dirname $0)/common.sh"

if [[ $2 == "" ]]; then
    author=$MY_USERNAME
    project_name=$1
else
    author=$1
    project_name=$2
fi

complete_name="$PROJECTS/$author/$project_name"

if [ -d "$complete_name" ]; then
    cd $complete_name
else
    echo -n "This project does not exist, would you like to clone it? [Y/n] "
    read response
    if [[ "$response" != "n" ]]; then
        echo "clone-github '$*'"
    fi
fi
