#!/bin/zsh
source "$(dirname $0)/common.sh"

project=$(projectify "$*")

mkdir -p "$PROJECTS/$project"

clonecmd="git clone git@github.com:$project.git $PROJECTS/$project"

in-new-tab "$clonecmd"

"$SCRIPTS/create-sublime-project" "$*"
