#!/bin/zsh
source "$(dirname $0)/common.sh"

project=$(projectify "$*")
project_path="$PROJECTS/$project"
project_file_name="$PROJECTS_INFOS/$(echo $project | sed "s,/,-,g").sublime-project"

project_file_content=$(cat "$DEFAULT_PROJECT" | sed "s,\[INSERTPATH\],$project_path,g")

echo $project_file_content > $project_file_name

# "$SCRIPTS/open-sublime-project" "$*"
