#!/bin/zsh
source "$(dirname $0)/common.sh"

has_terminal_running
running=$?

if [[ running -eq 1 ]]; then
    osascript -e 'tell application "Terminal" to activate' -e 'tell application "System Events" to tell process "Terminal" to keystroke "t" using command down' -e "tell application \"Terminal\" to do script \"$*\" in selected tab of the front window" > /dev/null
else
    osascript -e 'tell application "Terminal" to activate' -e "tell application \"Terminal\" to do script \"$*\" in selected tab of the front window" > /dev/null
fi

